### ISSUE TITLE
images are broken

### ISSUE THREAD

**Issue by sashastg** [anisurrahman072/React-Native-Advanced-Guide#5]
Hello,
Thanks for your work!

Just want you inform that images are broken.
for example here:
https://github.com/anisurrahman072/React-Native-Advanced-Guide/blob/master/Anti-Patterns/Nested-Virtualization-anti-pattern.md

https://github.com/anisurrahman072/React-Native-Advanced-Guide/blob/master/Anti-Patterns/Component-Call-anti-pattern.md

**Comment by anisurrahman072** [comment]
Thanks mate a lot. I see it just now. Yea images are broken. Let me see how fast I can solve it.

Actually images are coming from an another BLOG site which is Medium. Now, what is think i will save the Images directly to the repo & show them from the repo.

**Comment by anisurrahman072** [comment]
Hopefully the image breaking issue has been fixed in all Chapters ✅

Please let me know @sashastg, if that works or not 🚀

**Comment by sashastg** [comment]
> Hopefully the image breaking issue has been fixed in all Chapters ✅
> 
> Please let me know @sashastg, if that works or not 🚀

Yes now all ok!
Thanks for fast fixes!
Have a good day!

**Comment by anisurrahman072** [comment]
So far, I have fully merged all the remote images into local repo for this Guide. Will complete it for all other Guide too 👇
- [✅ 003 - Ultimate Guide on Component (JS) Testing by RNTL with Jest setup](https://github.com/anisurrahman072/React-Native-Advanced-Guide/blob/master/Testing/RNTL-Component-Testing-ultimate-guide.md)

### However, only one Guide took 42 Images which took me huge time ⏰
